name: Autoblack

on: [push, pull_request]

jobs:
  autoblack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
      - name: Install Black
        run: pip install black
      - name: Run black --check
        run: black --check .
      - name: Commit changes
        if: failure()
        run: |
          black .
          git config --global user.name "ybrenning"
          git config --global user.email "yannickbrenning2@gmail.com"

          git add -A
          git commit -m "Auto-reformatting"
          git push origin HEAD:master
